/// <reference types="expo/types" />

// Generated by Expo, and required for the editor to understand Expo globals --
// notably the typed `process.env.EXPO_PUBLIC_*` variables used in
// services/robotGateway.ts. Do not edit by hand.
